### ISSUE TITLE
npm module 'process' not installed

### ISSUE THREAD

**Issue by johnholbrook** [peterldowns/mathslax#10]
Not sure if this is an issue with mathslax, my configuration, or some combination thereof, but I thought I'd drop a message here anyway.

After installing mathslax according to the provided instructions on Ubuntu 14.04.5 LTS (including creating the link from /usr/bin/node -> /usr/bin/nodejs), attempting to start mathslax resulted in the following:

```
john@JohnServer:~/slack_math/mathslax$ SERVER=myurl PORT=9999 node server.js

module.js:340
    throw err;
          ^
Error: Cannot find module 'process'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Function.sre.SystemExternal.require (/home/john/slack_math/mathslax/node_modules/MathJax-node/node_modules/speech-rule-engine/lib/sre.js:53:256)
    at Object.<anonymous> (/home/john/slack_math/mathslax/node_modules/MathJax-node/node_modules/speech-rule-engine/lib/sre.js:53:403)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
```

`npm install process` seemed to resolve the issue.

**Comment by colbygk** [comment]
process is used indirectly and must be an issue on your system
