### ISSUE TITLE
mathslax doesn't work with node 7.4

### ISSUE THREAD

**Issue by rotten** [peterldowns/mathslax#8]
I'm having trouble getting mathslax to work with the newest version of node (on Ubuntu 16.04).  I have not tried it with other versions.

```
$  git clone https://github.com/colbygk/mathslax.git
Cloning into 'mathslax'...
$ cd mathslax
$ npm install
npm WARN deprecated jade@1.7.0: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm WARN deprecated transformers@2.1.0: Deprecated, use jstransformer

> contextify@0.1.15 install /home/mathnode/src/mathslax/node_modules/contextify
> node-gyp rebuild
```
<snip>
```
make: *** [Release/obj.target/contextify/src/contextify.o] Error 1
make: Leaving directory '/home/mathnode/src/mathslax/node_modules/contextify/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/mathnode/node-v7.4.0-linux-x64/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Linux 4.4.0-62-generic
gyp ERR! command "/home/mathnode/node-v7.4.0-linux-x64/bin/node" "/home/mathnode/node-v7.4.0-linux-x64/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/mathnode/src/mathslax/node_modules/contextify
gyp ERR! node -v v7.4.0
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
```

I've read after some googling that contextify is not required for modern node installations.  I'm not sure what is trying to install it though.  I've tried messing around with package.json to force newer versions of the supporting libraries, but I haven't gotten it to work yet.

**Comment by iblislin** [comment]
try this?
```diff
diff --git a/package.json b/package.json
index 58603dd..bd5c244 100644
--- a/package.json
+++ b/package.json
@@ -7,7 +7,6 @@
         "express": "4.0.0",
         "jade": "1.7.0",
         "q": "1.0.1",
-        "underscore": "1.7.0",
-        "jsdom": ">= 0.1.23 < 4.0.0"
+        "underscore": "1.7.0"
     }
 }
```
